name: CD

on: 
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      environment:
        required: true
        type: string
        
jobs:
  cd:
    name: App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          normalized_environment=$(echo ${{ inputs.environment }} | awk '{ print toupper($0) }')
          echo "::set-output name=NORMALIZED_ENVIRONMENT::$normalized_environment"
        id: normalized-environment
      - run: echo "${{ steps.normalized-environment.outputs.NORMALIZED_ENVIRONMENT }}"
      - name: Wait for Infra to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          allowed-conclusions: success,skipped
          check-name: CD - Infra - ${{ steps.normalized-environment.outputs.NORMALIZED_ENVIRONMENT }} / Infra
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.sha }}
          running-workflow-name: cd_hml
          wait-interval: 10
      - run: echo This is CD!
      - run: echo ${{ inputs.username }}
