name: CD - Infra

on: 
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  cd_infra:
    name: Infra
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: ${{ steps.get-envs.outputs.ENVIRONMENT_URL }}
      
    steps:
      - uses: actions/checkout@v2

      - run: echo This is CD Infra validate!
      
      - run: echo ${{ inputs.username }}
      
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: |
            src:
              - kube/${{ inputs.environment }}/infra.yaml
      
      - run: |
          sleep 20
          echo Infra changes!
        if: steps.changes.outputs.src == 'true'

      - run: echo '::set-output name=ENVIRONMENT_URL::https://google.com'
        if: always()
        id: get-envs
    

